backend:
  name: git-gateway
  branch: main # ou master selon ton dépôt

media_folder: "assets/images" # dossier de destination des médias
public_folder: "/assets/images"

collections:
  - name: "galerie"
    label: "Galerie"
    folder: "content/galerie"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Titre", name: "title", widget: "string" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Vidéo (lien)", name: "video", widget: "string", required: false }
      - { label: "Texte", name: "body", widget: "markdown", required: false }
